### ISSUE TITLE
Doesn't run on Python 2.7.9

### ISSUE THREAD

**Issue by FiZiX** [hackappcom/iloot#38]
The latest commit gives the following error when trying to run on Python 2.7.9:

`TypeError: __init__() got an unexpected keyword argument 'server_hostname'`

What is the target version of Python for this build?

**Comment by peterholko** [comment]
Same error for me.

**Comment by fitus** [comment]
same

**Comment by Marfusios** [comment]
It's strange, because in PyCharm IDE it works, but starting in console it doesn't. 
Tested on Mac 10.10.2.

**Comment by FiZiX** [comment]
It works with 2.7.8. I believe it's an issue with gevent. See here:

https://github.com/gevent/gevent/issues/477

**Comment by jamadden** [comment]
Try either the branch referenced in #551 or #552, depending on whether you want stable or master, in that order.

**Comment by dwkns** [comment]
Have confirmed this is an issue with 2.7.9. And I think @FiZiX is right about it being a gevent problem.

You can get round it by using [pyenv](https://github.com/yyuu/pyenv) 

On OS X :

	$ brew install  pyenv
	
Followed by :

	$ echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
	
Open a new terminal window. Then...

	$ pyenv install 2.7.8
	
To check :

	$ python --version
	>> Python 2.7.8

You'll probably need to update the requirements.

	$ cd iloot
	$ pip install -r requirements.txt
